// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQi1EDlu60PCJa0AhRKjiMx_r_x0VJSkk',
    appId: '1:918296015730:android:0c1a7dea766af7f1c723eb',
    messagingSenderId: '918296015730',
    projectId: 'corizo-flutter-tourapp',
    storageBucket: 'corizo-flutter-tourapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Y0lc9tPDet-oqv-SnbvIopFbVPybM-0',
    appId: '1:918296015730:ios:b55023f4ea6b8f31c723eb',
    messagingSenderId: '918296015730',
    projectId: 'corizo-flutter-tourapp',
    storageBucket: 'corizo-flutter-tourapp.firebasestorage.app',
    iosBundleId: 'com.corizo.flutterproject.tourRecommendationApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkHFVdvrf5QNVpgFXwi9f5Pcpg0k1EAVk',
    appId: '1:918296015730:web:8cb9864233bae3d4c723eb',
    messagingSenderId: '918296015730',
    projectId: 'corizo-flutter-tourapp',
    authDomain: 'corizo-flutter-tourapp.firebaseapp.com',
    storageBucket: 'corizo-flutter-tourapp.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Y0lc9tPDet-oqv-SnbvIopFbVPybM-0',
    appId: '1:918296015730:ios:b55023f4ea6b8f31c723eb',
    messagingSenderId: '918296015730',
    projectId: 'corizo-flutter-tourapp',
    storageBucket: 'corizo-flutter-tourapp.firebasestorage.app',
    iosBundleId: 'com.corizo.flutterproject.tourRecommendationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkHFVdvrf5QNVpgFXwi9f5Pcpg0k1EAVk',
    appId: '1:918296015730:web:efb11b5b1f10b057c723eb',
    messagingSenderId: '918296015730',
    projectId: 'corizo-flutter-tourapp',
    authDomain: 'corizo-flutter-tourapp.firebaseapp.com',
    storageBucket: 'corizo-flutter-tourapp.firebasestorage.app',
  );

}